// Application-only interrupted diagnostic package; original footage and records preserved.
import {readFile,writeFile,mkdir,readdir,cp} from 'node:fs/promises';
import {join,resolve,relative} from 'node:path';
import {createHash} from 'node:crypto';
import {inspectRecording,mapEventFrame} from './live-smoke-timeline.js';
const root=resolve(process.argv[2]!),out=join(root,'diagnostic-review');
const entries=await readdir(root);await mkdir(out);
for(const name of entries)await cp(join(root,name),join(out,'evidence',name),{recursive:true});
const original=join(out,'evidence/trajectory-retained-0/original.mp4');
const media=await inspectRecording(original,resolve(original,'../ffmpeg.log'));
const packageDir=(await readdir(join(out,'evidence/packages')))[0]!;
const pkg=join(out,'evidence/packages',packageDir);
const review=JSON.parse(await readFile(join(pkg,'trajectory.json'),'utf8'));
const journal=(await readFile(join(pkg,'state/journal/events.jsonl'),'utf8')).trim().split('\n').map(x=>JSON.parse(x));
const manifest=JSON.parse(await readFile(join(pkg,'manifest.json'),'utf8'));
const app=(await readFile(resolve(original,'../events.jsonl'),'utf8')).trim().split('\n').map(x=>JSON.parse(x));
let appIndex=0;
const steps=review.steps.map((s:any)=>{const a=journal.find(x=>x.kind==='action-start'&&x.actionId===s.actionId),b=journal.find(x=>x.kind==='action-completion'&&x.actionId===s.actionId);const ui=s.id!=='disable-overlay';const start=ui?app.filter(x=>x.phase==='start')[appIndex++]:null;const end=start?app.find(x=>x.phase==='end'&&x.start===start.utcMs):null;const from=start?.utcMs??Date.parse(a.writtenAt),to=end?.utcMs??Date.parse(b.writtenAt);const observation=Math.max(to,Date.parse(manifest.snapshots.find((x:any)=>x.path===s.snapshots.after).capturedAt));return {...s,recordingId:'diagnostic-original',actionInterval:{start:mapEventFrame(media.frames,from).mediaSeconds,end:mapEventFrame(media.frames,to).mediaSeconds},observationPoint:mapEventFrame(media.frames,observation,'following').mediaSeconds,utcMs:{from,to,observation},observed:s.id==='diagnostic-navigation'?'Dispatch completed and active Chromium title advanced, but original CUA/root captures remained frozen. This is a capture defect, not a successful visible-navigation claim.':s.id==='diagnostic-dom'?'Server-owned browser read returned the fixture body on the same browser. No CDP or separate browser attachment.':'Documented stop then serve --no-overlay completed once. Its 1000ms after-snapshot still showed stale pixels; later independent root and CUA captures showed the fixture. Preserve this observation delay instead of replacing the causal snapshot.',execution:ui?'completed-with-capture-defect':'completed',footageReview:'pending'};});
const observe=JSON.parse(await readFile(resolve(original,'../after-no-overlay-observations.json'),'utf8'));
steps.push({id:'independent-capture-restored',title:'Independent capture restored after documented correction',expected:'Current fixture appears in independent root and CUA output',observed:'Both outputs changed; local OCR recognizes Relay Ubuntu verification, Type relay here and Waiting for input. This corroborates content, not human visual approval.',execution:'completed',recordingId:'diagnostic-original',actionInterval:{start:mapEventFrame(media.frames,observe.startedUtcMs).mediaSeconds,end:mapEventFrame(media.frames,observe.finishedUtcMs).mediaSeconds},observationPoint:mapEventFrame(media.frames,observe.finishedUtcMs,'following').mediaSeconds,footageReview:'pending'});
const error=JSON.parse(await readFile(join(root,'error.json'),'utf8'));
const data={formatVersion:1,outcomes:{recording:'complete-original',execution:'incomplete-harness-error',captureDiagnosis:'default-overlay-freezes-X11; documented no-overlay restores content',humanReview:'pending',cleanup:'verified'},error,recording:{id:'diagnostic-original',path:relative(out,original),duration:media.duration,width:media.stream.width,height:media.stream.height,frameTimeline:media.frames,mapping:'Action: preceding source frame; observation: following source frame; exact original source/decoded timestamps retained; first captured frame defines zero.',mappingErrorFormula:media.mappingErrorFormula,maximumMappingErrorSeconds:media.maximumMappingErrorSeconds},steps};
await writeFile(join(out,'trajectory.json'),JSON.stringify(data,null,2));
await writeFile(join(out,'OPENING.txt'),'Open index.html directly. Original video, interrupted diagnostic, corrections, receipts and later observations retained. No screenshots were replaced. Diagnostic ended on a malformed read-only command; no uncertain input replay. Human review pending.\n');
await writeFile(join(out,'index.html'),`<!doctype html><meta charset="utf-8"><title>Linux capture diagnosis</title><style>body{font:16px system-ui;margin:24px;color:#123}main{display:grid;grid-template-columns:2fr 1fr;gap:24px}video{width:100%;position:sticky;top:16px}article{padding:16px;border:1px solid #abc;margin:14px 0}.current{outline:3px solid #178}button{padding:8px}.warning{background:#ffe9dc;padding:16px}</style><h1>Linux capture diagnosis — original attempt</h1><p class="warning">Recording complete; diagnostic ended incomplete on a malformed read-only command. Default overlay froze capture; documented no-overlay restored fixture content. Human review pending.</p><p><a href="manifest.json">Checksums</a> · <a href="trajectory.json">Exact frame mapping and steps</a></p><main><section><video id="video" controls></video></section><section><button id="prev">Previous</button> <button id="next">Next</button><div id="steps"></div></section></main><script>const d=${JSON.stringify(data).replace(/</g,'\\u003c')},v=document.querySelector('#video');v.src=d.recording.path;let n=0;const cards=[];function pick(i,seek=true){n=Math.max(0,Math.min(i,d.steps.length-1));cards.forEach((e,j)=>e.classList.toggle('current',j===n));if(seek){v.currentTime=Math.max(0,d.steps[n].actionInterval.start-1);history.replaceState(null,'','#step-'+d.steps[n].id)}}d.steps.forEach((s,i)=>{const a=document.createElement('article'),b=document.createElement('button');b.textContent=s.title;b.onclick=()=>pick(i);a.append(b);for(const t of ['Expected: '+s.expected,'Observed: '+s.observed,'Execution: '+s.execution,'Result at '+s.observationPoint.toFixed(3)+' seconds']){const p=document.createElement('p');p.textContent=t;a.append(p)}const l=document.createElement('a');l.href='#step-'+s.id;l.textContent='Stable step link';l.onclick=e=>{e.preventDefault();pick(i)};a.append(l);document.querySelector('#steps').append(a);cards.push(a)});document.querySelector('#prev').onclick=()=>pick(n-1);document.querySelector('#next').onclick=()=>pick(n+1);v.ontimeupdate=()=>{const i=d.steps.findLastIndex(s=>s.actionInterval.start<=v.currentTime);if(i>=0)pick(i,false)};v.onloadedmetadata=()=>{const i=d.steps.findIndex(s=>'#step-'+s.id===location.hash);pick(Math.max(0,i))};pick(0,false);</script>`);
async function files(dir:string):Promise<string[]>{const out:string[]=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory())out.push(...await files(p));else if(e.isFile())out.push(p);else throw Error('Nonregular file');}return out;}
const inventory=[];for(const p of await files(out)){const b=await readFile(p);inventory.push({path:relative(out,p),bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});}
await writeFile(join(out,'manifest.json'),JSON.stringify({formatVersion:1,outcomes:data.outcomes,recordings:[data.recording],files:inventory},null,2));
for(const f of inventory){const b=await readFile(join(out,f.path));if(b.length!==f.bytes||createHash('sha256').update(b).digest('hex')!==f.sha256)throw Error('Hash mismatch');}
console.log(JSON.stringify({out,filesVerified:inventory.length,outcomes:data.outcomes}));
