// Application-only portable video review builder. Never changes the relay package.
import {readFile,writeFile,mkdir,readdir,cp,stat} from 'node:fs/promises';
import {join,resolve,relative} from 'node:path';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {verifyDeliveredPackage} from '../src/package.js';
import {inspectRecording,mapEventFrame} from './live-smoke-timeline.js';
if(process.argv[2]==='--verify-media'){
 const video=resolve(process.argv[3]!);const result=await inspectRecording(video,resolve(video,'../ffmpeg.log'));
 for(let i=0;i<result.frames.length-1;i++){const f=result.frames[i]!,next=result.frames[i+1]!;const epochMs=Math.ceil(f.sourceFrameEpochUs/1000);if(epochMs*1000<next.sourceFrameEpochUs&&mapEventFrame(result.frames,epochMs).frame!==f.frame)throw Error('Preceding frame mapping mismatch');}
 console.log(JSON.stringify(result,null,2));process.exit(0);
}
const root=resolve(process.argv[2]!),output=join(root,'trajectory-review');
const finish=JSON.parse(await readFile(join(root,'finish.json'),'utf8'));const source=resolve(finish.manifestPath,'..');
const verified=await verifyDeliveredPackage(source);if(verified.execution!=='passed'||verified.snapshots!=='complete')throw Error('Relay package did not fully pass');
await mkdir(output);await cp(source,join(output,'evidence'),{recursive:true});await verifyDeliveredPackage(join(output,'evidence'));
async function all(dir:string):Promise<string[]>{const out:string[]=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory())out.push(...await all(p));else if(e.isFile())out.push(p);else throw Error('Nonregular artifact');}return out.sort();}
const files=await all(join(output,'evidence'));const video=files.find(p=>p.endsWith('/original.mp4'));if(!video)throw Error('Original recording missing');const walk=resolve(video,'..');
const {stream,duration,frames,maximumMappingErrorSeconds:maxError,mappingErrorFormula}=await inspectRecording(video,join(walk,'ffmpeg.log'));
const review=JSON.parse(await readFile(join(output,'evidence/trajectory.json'),'utf8'));
const journal=(await readFile(join(output,'evidence/state/journal/events.jsonl'),'utf8')).trim().split('\n').map(x=>JSON.parse(x));
const application=(await readFile(join(walk,'events.jsonl'),'utf8')).trim().split('\n').map(x=>JSON.parse(x));
const actions=application.filter(e=>e.phase==='start').map(e=>({...e,end:application.find(x=>x.phase==='end'&&x.start===e.utcMs&&x.tool===e.tool)}));
const starts=journal.filter(e=>e.kind==='action-start');const snapshots=JSON.parse(await readFile(join(output,'evidence/manifest.json'),'utf8')).snapshots;
const steps:any[]=[];let app=0;await mkdir(join(output,'review-frames'));
for(const s of review.steps){const start=starts.find(e=>e.actionId===s.actionId),end=journal.find(e=>e.kind==='action-completion'&&e.actionId===s.actionId);if(!start||!end)throw Error('Missing guest action interval');const isUI=!['exec-smoke','uploaded-script','streamed-code'].includes(s.id);const event=isUI?actions[app++]:undefined;if(isUI&&!event?.end)throw Error('Missing application input interval');const beginMs=event?.utcMs??Date.parse(start.writtenAt),endMs=event?.end.utcMs??Date.parse(end.writtenAt);if(endMs<beginMs)throw Error('Reversed original action timestamps');const beginFrame=mapEventFrame(frames,beginMs),endFrame=mapEventFrame(frames,endMs);const from=beginFrame.mediaSeconds,to=endFrame.mediaSeconds;const snapshot=snapshots.find((x:any)=>x.path===s.snapshots?.after);if(!snapshot)throw Error('Missing after-snapshot observation timestamp');const observationUtcMs=Math.max(Date.parse(snapshot.capturedAt),endMs);const observationFrame=mapEventFrame(frames,observationUtcMs,'following');const observe=observationFrame.mediaSeconds;if(!(from>=0&&to>=from&&observe<duration&&observe>=to))throw Error(`Timestamp bounds invalid: ${s.id}`);const frame=`review-frames/${s.id}.png`;execFileSync('ffmpeg',['-v','error','-ss',String(observe),'-i',video,'-frames:v','1',join(output,frame)]);steps.push({...s,recordingId:'ubuntu-original',actionInterval:{start:from,end:to},observationPoint:observe,frameReferences:{actionStart:beginFrame.frame,actionEnd:endFrame.frame,observation:observationFrame.frame},originalEpochMs:{start:beginMs,end:endMs,observation:observationUtcMs},utc:{start:new Date(beginMs).toISOString(),end:new Date(endMs).toISOString(),observation:new Date(observationUtcMs).toISOString()},supportingEvidence:[frame,'evidence/state/journal/events.jsonl',relative(output,join(walk,'events.jsonl'))],footageReview:'pending',evidenceScope:isUI?'Guest browser/CUA dispatch interval and full-display footage; visible result requires review.':'Non-UI execution established by receipt/log; footage demonstrates desktop continuity only.'});}
if(app!==actions.length)throw Error('Unmatched application events');
const data={formatVersion:1,recording:{id:'ubuntu-original',path:relative(output,video),width:stream.width,height:stream.height,duration,firstCapturedFrameEpochUs:frames[0]!.sourceFrameEpochUs,formula:'actionMediaSeconds = decodedMediaPtsSeconds[max(frame where sourceFrameEpochUs <= guestEventEpochMs * 1000)]',observationFormula:'observationMediaSeconds = decodedMediaPtsSeconds[min(frame where sourceFrameEpochUs >= observationEpochMs * 1000)]',mapping:'Exact source and decoded timestamps retained per frame; equal frame counts, contiguous source ordinals and strictly increasing source/media PTS required. Action endpoints use nearest preceding source frame; observation uses first following frame. No timestamp interpolation or constant-offset assumption.',frameTimeline:frames,maximumMappingErrorSeconds:maxError,mappingErrorFormula,frameCount:frames.length},outcomes:{recording:'complete',execution:'passed',humanReview:'pending'},steps};
await writeFile(join(output,'trajectory.json'),JSON.stringify(data,null,2));
const encoded=JSON.stringify(data).replace(/</g,'\\u003c');
await writeFile(join(output,'index.html'),`<!doctype html><meta charset="utf-8"><title>Ubuntu relay live trajectory</title><style>body{font:16px system-ui;margin:20px;background:#f5f7fb;color:#123}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(340px,1fr);gap:24px}video{width:100%;position:sticky;top:16px;background:#000}article{padding:16px;border:1px solid #bbc;margin:12px 0;background:white}article.current{outline:3px solid #168}button{padding:8px;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere}.failed,.incomplete,.blocked{background:#fee}a{color:#057}@media(max-width:900px){main{display:block}}</style><h1>Ubuntu relay — application video trajectory</h1><p>Recording: complete · Execution: passed · Human review: pending. Video is test-harness evidence, not an extension feature.</p><p><a href="manifest.json">Checksums</a> · <a href="trajectory.json">Structured timeline</a> · <a href="evidence/index.html">Original relay snapshot review</a></p><main><section><video controls id="video"></video><p id="caption"></p></section><section><button id="prev">Previous</button> <button id="next">Next</button><div id="steps"></div></section></main><script>const data=${encoded},v=document.querySelector('#video'),holder=document.querySelector('#steps');v.src=data.recording.path;let selected=0;const cards=[];function choose(i,seek=true){selected=Math.max(0,Math.min(i,data.steps.length-1));const s=data.steps[selected];cards.forEach((c,n)=>c.classList.toggle('current',n===selected));document.querySelector('#caption').textContent=s.title+' — '+s.execution;if(seek){v.currentTime=Math.max(0,s.actionInterval.start-1);history.replaceState(null,'','#step-'+encodeURIComponent(s.id));}}data.steps.forEach((s,i)=>{const a=document.createElement('article');a.id='step-'+s.id;a.className=s.execution;const b=document.createElement('button');b.textContent=s.title;b.onclick=()=>choose(i);a.append(b);for(const text of ['Action / expected: '+s.expected,'Observed: '+s.observed,'Execution: '+s.execution+' · Input: '+s.inputMode,'Action interval: '+s.actionInterval.start.toFixed(3)+'–'+s.actionInterval.end.toFixed(3)+' seconds; result at '+s.observationPoint.toFixed(3)+' seconds.',s.evidenceScope]){const p=document.createElement('p');p.textContent=text;a.append(p)}const link=document.createElement('a');link.href='#step-'+encodeURIComponent(s.id);link.textContent='Stable step link';link.onclick=e=>{e.preventDefault();choose(i)};a.append(link);holder.append(a);cards.push(a)});v.ontimeupdate=()=>{let i=data.steps.findLastIndex(s=>s.actionInterval.start<=v.currentTime);if(i>=0)choose(i,false)};document.querySelector('#prev').onclick=()=>choose(selected-1);document.querySelector('#next').onclick=()=>choose(selected+1);function hash(){const id=decodeURIComponent(location.hash.slice(6));const i=data.steps.findIndex(s=>s.id===id);if(i>=0)choose(i)}window.onhashchange=hash;v.onloadedmetadata=hash;choose(0,false);</script>`);
await writeFile(join(output,'OPENING.txt'),'Open index.html directly in a browser. All media, original relay evidence, steps and hashes are local. Timeline zero is the first captured frame, not recorder launch. Original MP4 was not transcoded. Human review remains pending.\n');
const inventory=[];for(const p of await all(output)){const b=await readFile(p);inventory.push({path:relative(output,p),bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});}await writeFile(join(output,'manifest.json'),JSON.stringify({formatVersion:1,packageType:'application-trajectory',...data.outcomes,recordings:[data.recording],files:inventory},null,2));
for(const f of inventory){const b=await readFile(join(output,f.path));if(b.length!==f.bytes||createHash('sha256').update(b).digest('hex')!==f.sha256)throw Error('Post-build checksum changed');}
console.log(JSON.stringify({output,steps:steps.length,recording:'complete',execution:'passed',humanReview:'pending',formula:data.recording.formula,maximumMappingErrorSeconds:maxError},null,2));
