// Checks the npm tarball that will be published, not the working tree.
//
//   node scripts/verify-package.mjs [package.tgz] [--version X.Y.Z]
//
// Without a tarball it packs one into a temporary directory. The release
// workflow packs once, runs this on that file, then publishes and attaches the
// same file, so what was checked is exactly what ships. Exit code 1 lists every
// failed check.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { COMMAND_DIRS, COMMANDS, hostCommandFiles, piCommandName } from './host-commands.mjs';

const args = process.argv.slice(2);
const versionAt = args.indexOf('--version');
const expectedVersion = versionAt >= 0 ? args.splice(versionAt, 2)[1] : undefined;
const work = mkdtempSync(join(tmpdir(), 'mcp-vm-relay-verify-'));
const failures = [];
const check = (ok, message) => { if (!ok) failures.push(message); };

try {
  let tarball = args[0] && resolve(args[0]);
  if (!tarball) {
    execFileSync('npm', ['pack', '--silent', '--pack-destination', work], { stdio: ['ignore', 'ignore', 'inherit'] });
    tarball = join(work, readdirSync(work).find(name => name.endsWith('.tgz')));
  }
  execFileSync('tar', ['-xzf', tarball, '-C', work]);
  const root = join(work, 'package');
  const read = path => readFileSync(join(root, path), 'utf8');
  const has = path => existsSync(join(root, path));
  const json = path => JSON.parse(read(path));

  // 1. Versions: package.json, the Claude Code plugin, the pinned pi server, and the tag.
  const pkg = json('package.json');
  check(pkg.name === '@wezzard/mcp-vm-relay', `package name is ${pkg.name}`);
  if (expectedVersion) check(pkg.version === expectedVersion, `package version ${pkg.version} differs from the tag ${expectedVersion}`);
  check(json('.claude-plugin/plugin.json').version === pkg.version, '.claude-plugin/plugin.json version differs from package.json');
  const pinned = json('pi-mcp.json').mcpServers?.relay?.args ?? [];
  check(pinned.includes(`@wezzard/mcp-vm-relay@${pkg.version}`), `pi-mcp.json does not pin @wezzard/mcp-vm-relay@${pkg.version}`);
  check(has('.mcp.json') && has('dist/server.mjs'), '.mcp.json or dist/server.mjs is missing');

  // 2. Host command files: present, byte-identical to the generator, nothing extra.
  const expected = hostCommandFiles();
  for (const [path, content] of Object.entries(expected)) {
    if (!has(path)) { failures.push(`${path} is missing`); continue; }
    check(read(path) === content, `${path} differs from scripts/host-commands.mjs; run npm run build and commit`);
    const [, frontmatter] = read(path).split(/^---$/m);
    for (const line of frontmatter.trim().split('\n')) {
      const key = line.slice(0, line.indexOf(':'));
      check(['description', 'argument-hint'].includes(key), `${path}: unexpected front matter key "${key}"`);
      try { JSON.parse(line.slice(line.indexOf(':') + 1).trim()); } catch { failures.push(`${path}: the value of "${key}" is not a quoted string`); }
    }
  }
  for (const dir of Object.values(COMMAND_DIRS)) {
    for (const name of has(dir) ? readdirSync(join(root, dir)) : []) check(`${dir}/${name}` in expected, `${dir}/${name} is not generated by scripts/host-commands.mjs`);
  }

  // 3. pi finds exactly its prompt templates through the manifest's globs.
  const globs = pkg.pi?.prompts ?? [];
  check(pkg.pi?.mcp === './pi-mcp.json', 'package.json pi.mcp is not ./pi-mcp.json');
  const toRegex = glob => {
    if (/[?[\]{}]|\*\*/.test(glob)) failures.push(`pi.prompts glob ${glob} uses syntax this check does not model`);
    return new RegExp(`^${glob.replace(/^\.\//, '').replace(/[.+^$()|\\]/g, '\\$&').replace(/\*/g, '[^/]*')}$`);
  };
  const piFiles = has(COMMAND_DIRS.pi) ? readdirSync(join(root, COMMAND_DIRS.pi)).map(name => `${COMMAND_DIRS.pi}/${name}`) : [];
  const found = piFiles.filter(path => globs.some(glob => toRegex(glob).test(path))).sort();
  const wanted = COMMANDS.map(command => `${COMMAND_DIRS.pi}/${piCommandName(command.name)}.md`).sort();
  check(JSON.stringify(found) === JSON.stringify(wanted), `pi.prompts ${JSON.stringify(globs)} selects ${JSON.stringify(found)}, expected ${JSON.stringify(wanted)}`);

  // 4. No leftovers from earlier designs.
  check(!has('skills') && !has('hooks'), 'the package ships skills/ or hooks/');

  // 5. The packed server starts, offers every tool a command names, and no MCP prompts.
  const transport = new StdioClientTransport({ command: process.execPath, args: [join(root, 'dist', 'server.mjs')], cwd: work, env: { ...process.env, MCP_VM_RELAY_PROJECT: work, MCP_VM_RELAY_SESSION: 'verify-package' }, stderr: 'ignore' });
  const client = new Client({ name: 'verify-package', version: '1' });
  await client.connect(transport);
  try {
    check(client.getServerCapabilities()?.prompts === undefined, 'the server still declares the MCP prompts capability');
    const tools = new Set((await client.listTools()).tools.map(tool => tool.name));
    for (const command of COMMANDS) check(tools.has(command.tool), `command ${command.name} names ${command.tool}, which the server does not offer`);
    check(client.getServerVersion()?.version === pkg.version, `the server reports version ${client.getServerVersion()?.version}, not ${pkg.version}`);
  } finally { await client.close(); }

  if (failures.length) { console.error(`Package check failed for ${tarball}:\n- ${failures.join('\n- ')}`); process.exitCode = 1; }
  else console.log(`Package check passed for ${tarball} (${pkg.name}@${pkg.version})`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
